export interface PluginConfig {
  maxConcurrentSessions: number
}

export interface Downstream {
  id: string
  repo: string                          // "owner/web-app"
  branch: string                        // "main"
  telegramTopicId: number
  issueLabels: string[]
  promptTemplate: string
  agent: string                         // Claude model name
  sessionStrategy: 'per-trigger' | 'rolling' | 'persistent'
  sessionLimits: {
    maxTurns: number                    // default 10
    maxAge: string                      // default "24h" (ms-parseable)
  }
  currentSessionId?: string
  sessionTurnCount?: number
  sessionCreatedAt?: string
}

export interface Watcher {
  id: string                            // "watcher_abc123"
  upstream: {
    repo: string                        // "owner/backend"
    branch: string
    webhookId: number
    webhookSecret: string               // random 32-char hex
  }
  downstreams: Downstream[]
  createdAt: string
}

export interface QueueItem {
  id: string                            // "job_def456"
  watcherId: string
  downstreamId: string
  prNumber: number
  prUrl: string
  deliveryId: string                    // X-GitHub-Delivery header value
  enqueuedAt: string
  status: 'pending' | 'processing' | 'done' | 'failed'
  attempts: number
  retryAfter?: string                   // ISO timestamp
  error?: string
}

export interface RunLogEntry {
  jobId: string
  watcherId: string
  downstreamId: string
  upstream: string
  downstream: string
  prNumber: number
  prUrl: string
  sessionId: string
  startedAt: string
  completedAt?: string
  status: 'success' | 'skipped' | 'failed'
  issueUrl?: string
  skipReason?: string
  error?: string
}

// Patterns use micromatch glob syntax with ** to cross path separators.
// Union {a,b} syntax handles commands with optional slash-containing args.
// Glob patterns matched against bash command descriptions. The micromatch
// union `{a,a/**}` handles commands whose args may or may not contain slashes
// (since `*` does not cross `/`).
export const AUTO_APPROVED_COMMANDS = [
  // All gh CLI subcommands (pr view/diff, issue create/list, api, auth, ...)
  '{gh,gh *,gh */**}',
  // Read-only git operations inside the workspace
  'git -C */**',
  // Common file-reading tools used for code exploration
  'cat */**',
  'grep * */**',
  'find */**',
  'ls */**',
] as const

export const DEFAULT_PROMPT_TEMPLATE = `PR #{pr_number} was merged into {upstream_repo}@{upstream_branch}.
- PR: {pr_url}
- Downstream under review: {downstream_repo}@{downstream_branch} (./downstream/)
- Upstream mirror: ./upstream/
- Issue labels to use when creating: {issue_labels}

Follow the method in the system prompt. If you conclude there is no real impact on {downstream_repo}, output \`ISSUE_SKIPPED: <reason>\` — do not create an issue.

If you do create an issue, use this shape:
- Title: \`[sync] Impact of PR #{pr_number}: <short summary>\`
- Labels: \`{issue_labels}\`
- Body sections (in order):
  1. One-line summary of the upstream change
  2. Impact analysis — specific files/symbols in {downstream_repo} that need attention, each with a short rationale
  3. TODO checklist of concrete follow-up tasks
  4. Footer: \`*🤖 Auto-generated by [git-watcher] · [Upstream PR #{pr_number}]({pr_url})*\`

Create with: \`gh issue create --repo {downstream_repo} --title "<title>" --body "<body>" --label "{issue_labels}"\``
