export interface PluginConfig {
  maxConcurrentSessions: number
}

export interface Downstream {
  id: string
  repo: string                          // "owner/web-app"
  branch: string                        // "main"
  telegramTopicId: number
  issueLabels: string[]
  promptTemplate: string
  agent: string                         // Claude model name
  sessionStrategy: 'per-trigger' | 'rolling' | 'persistent'
  sessionLimits: {
    maxTurns: number                    // default 10
    maxAge: string                      // default "24h" (ms-parseable)
  }
  currentSessionId?: string
  sessionTurnCount?: number
  sessionCreatedAt?: string
}

export interface Watcher {
  id: string                            // "watcher_abc123"
  upstream: {
    repo: string                        // "owner/backend"
    branch: string
    webhookId: number
    webhookSecret: string               // random 32-char hex
  }
  downstreams: Downstream[]
  createdAt: string
}

export interface QueueItem {
  id: string                            // "job_def456"
  watcherId: string
  downstreamId: string
  prNumber: number
  prUrl: string
  deliveryId: string                    // X-GitHub-Delivery header value
  enqueuedAt: string
  status: 'pending' | 'processing' | 'done' | 'failed'
  attempts: number
  retryAfter?: string                   // ISO timestamp
  error?: string
}

export interface RunLogEntry {
  jobId: string
  watcherId: string
  downstreamId: string
  upstream: string
  downstream: string
  prNumber: number
  prUrl: string
  sessionId: string
  startedAt: string
  completedAt?: string
  status: 'success' | 'failed'
  issueUrl?: string
  error?: string
}

// Patterns use micromatch glob syntax with ** to cross path separators.
// Union {a,b} syntax handles commands with optional slash-containing args.
export const AUTO_APPROVED_COMMANDS = [
  '{gh pr view *,gh pr view */**}',
  '{gh pr diff *,gh pr diff */**}',
  'gh auth status',
  'git -C */**',
  'cat */**',
  'grep * */**',
  'find */**',
  'ls */**',
] as const

export const DEFAULT_PROMPT_TEMPLATE = `A PR was merged in the upstream repository {upstream_repo}:
- PR URL: {pr_url}
- Branch: {upstream_branch}

Your task:
1. Read the PR details:
   gh pr view {pr_number} --repo {upstream_repo} --json title,body,files,additions,deletions
2. Read the diff:
   gh pr diff {pr_number} --repo {upstream_repo}
3. Check if an issue already exists for this PR:
   gh issue list --repo {downstream_repo} --search "Impact of PR #{pr_number}" --json number,url
4. Explore the downstream codebase in ./downstream/ to identify affected areas
5. Create an issue in {downstream_repo}:
   gh issue create --repo {downstream_repo} \\
     --title "[sync] Impact of PR #{pr_number}: <short summary>" \\
     --body "<your analysis with checklist>" \\
     --label "{issue_labels}"

The issue body must end with:
---
*🤖 Auto-generated by [git-watcher] · [Upstream PR #{pr_number}]({pr_url})*

When done, output on its own line: ISSUE_CREATED: <url>
If issue already existed, output: ISSUE_EXISTS: <url>
Stop after outputting one of these lines.`
